---
language: minimal
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.22.0
services:
- docker
branches:
  only:
  - master
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
stages:
  - deploy
jobs:
  include:
  - stage: deploy
    name: Deploy the blog up to AWS
    script:
      - git clone https://github.com/carlosonunez/https-hugo-bloggen blog-gen
      - cd blog-gen
      - rm -rf static config.toml.tmpl
      - mkdir content
      - cp -frv ../static/ static
      - cp -frv ../content/* content/
      - cp -frv ../layouts/* layouts/
      - cp ../config.toml.tmpl config.toml.tmpl
      - COMMIT_SHA=$(git rev-parse HEAD | head -c8) make create_site_folder_so_travis_works
      - COMMIT_SHA=$(git rev-parse HEAD | head -c8) make deploy
notifications:
  email:
    recipients:
      - dev@carlosnunez.me
    on_success: true
    on_failure: true

