---
language: minimal
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.22.0
services:
- docker
branches:
  only:
  - master
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
stages:
  - deploy
jobs:
  include:
  - stage: deploy
    name: Deploy the blog up to AWS
    script:
      - git clone https://github.com/carlosonunez/https-hugo-bloggen
      - docker-compose run --rm get-production-env
      - docker-compose run --rm deploy-blog
