version: "3.4"
services:
  travis:
    image: skandyla/travis-cli
    volumes:
      - "$PWD:/app"
      - "$HOME/.travis:/root/.travis"
    working_dir: /app
  wait-for-blog:
    image: byrnedo/alpine-curl
    network_mode: host
    entrypoint:
      - sh
      - "-c"
      - "until curl -o /dev/null -s localhost:8080; do echo -ne 'Waiting for site...\r' && sleep 1; done; echo -ne 'Waiting for site...ready.\n'"
  local-blog:
    ports:
      - 8080:8080
    network_mode: host
    build:
      context: ../https-hugo-bloggen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${PWD}/../https-hugo-bloggen:/app"
      - "${PWD}/.env.test:/app/.env"
    working_dir: /app
    environment:
      - HOST_PWD=${PWD}
      - VERBOSE=true
    command: start_local_blog
