[security]
  enableInlineShortcodes = true

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$','.*_HANDLE$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
