---
name: Deploy carlosnunez.me
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - scripts
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: KengoTODA/actions-setup-docker-compose@main
        name: Set up Docker Compose
        with:
          version: '2.27.1'

      - name: Fetch blog-gen
        env:
          BLOG_GEN_VERSION: 2.2.0
        run: >-
          git clone -b "v${BLOG_GEN_VERSION}" https://github.com/carlosonunez/https-hugo-bloggen blog-gen

      - name: Decrypt environment file
        run: ./blog-gen/scripts/decrypt_env.sh
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Deploy the blog
        run: ./blog-gen/scripts/deploy
