---
name: Deploy Carlos's Blog
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Docker Compose
        run: curl -L ${DOCKER_COMPOSE_URL}/docker-compose-`uname -s`-`uname -m` > ./docker-compose &&
          chmod +x ./docker-compose
        env:
          DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.29.0

      - name: Fetch blog-gen
        env:
          BLOG_GEN_VERSION: 2.0.9
        run: >-
          make fetch_blog_gen

      - name: Decrypt environment file
        run: make decrypt_env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Deploy the blog
        run: make deploy
